---
title: "Riboseq_quantseq_figures"
author: "Oscar Wilkins"
date: "19/03/2021"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning=FALSE)
if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load("tidyverse", "here")
```

## 6 Way Heatmap of differential RFP data

This code generates a 6-way heatmap of the RFP data. It reads in the processed data, which is produced by the script ""all_riboseq_quantseq_preprocessing.R" 

```{r 6wayRFP}

sq_lg2 <- read_csv(paste0(here(), "/data/square_lg2.csv"))

all_comparisons <- sq_lg2 %>%
  pivot_longer(cols = c("A", "B", "C", "D", "E", "G"), 
               names_to="reference",
               values_to = "log2fold") %>%
  filter(!is.na(log2fold))

ggplot(all_comparisons, aes(x = reference, y = comparison)) + 
  geom_tile(aes(fill=log2fold)) +
  scale_fill_gradient2(low="blue", mid= "white" ,high="red", midpoint=0,
                       limits = c(-2,2), breaks =c(-2, -1, 0, 1, 2))  +
  theme_minimal() +
  ggtitle("Pair-wise comparison of number of RFPs aligning to MAPT gene") +
  xlab("Reference Sample") +
  ylab("Comparison Sample")

```

## Riboseq volcano plot

This reads in the DESEQ2 values from data generated by "all_riboseq_quantseq_preprocessing.R"

```{r, rfp_volcano}

rfp_data <- read_csv(paste0(here(), "/data/RFP_A_vs_B_volcano_data.csv"))

min_counts_per_sample_average <- 10
min_counts <- min_counts_per_sample_average*17

ggplot(rfp_data, aes(log2FoldChange, minus_log10_p, colour = color, name=name)) +
  geom_point(size=1, alpha = 1) +
  ggtitle(paste0("Volcano plot of condition B versus A with minimum \n", min_counts, " counts total across 17 samples")) +
  scale_colour_identity() +
  theme_minimal() +
  geom_text(aes(label=name),hjust=0.6, vjust=1.2, size =3)

```
